SET C51INC=E:\Keil_v5\C51\Inc;E:\Keil_v5\C51\Inc\Cast
SET C51LIB=E:\Keil_v5\C51\Lib
SET CPU_TYPE=R8051XC2
SET CPU_VENDOR=CAST, Inc.
SET UV2_TARGET=CA51F
SET CPU_XTAL=0x016E3600
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\main.__i"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\INTERR~1.__I"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\CONTUR~1.__I"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\SYSTEM~1.__I"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\STOP_I~1.__I"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\pwm.__i"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\delay.__i"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\rtc.__i"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\uart.__i"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\lcd.__i"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\wdt.__i"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\Key.__i"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\music.__i"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\led.__i"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\debug.__i"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\ts_api.__i"
"E:\Keil_v5\C51\BIN\LX51.EXE" @".\hex\ca51fx.lnp"
"E:\Keil_v5\C51\BIN\OHX51.EXE" ".\hex\ca51fx" HEX
