SET C51INC=E:\Keil_v5\C51\Inc;E:\Keil_v5\C51\Inc\Cast
SET C51LIB=E:\Keil_v5\C51\Lib
SET CPU_TYPE=R8051XC2
SET CPU_VENDOR=CAST, Inc.
SET UV2_TARGET=CA51F
SET CPU_XTAL=0x016E3600
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\main.__i"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\delay.__i"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\SYSTEM~1.__I"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\uart.__i"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\INTERR~1.__I"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\CONTUR~1.__I"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\pwm.__i"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\debug.__i"
"E:\Keil_v5\C51\BIN\C51.EXE" @".\hex\ts_api.__i"
"E:\Keil_v5\C51\BIN\A51.EXE" @".\hex\STARTUP._ia"
"E:\Keil_v5\C51\BIN\LX51.EXE" @".\hex\HP-01-~1.LNP"
"E:\Keil_v5\C51\BIN\OHX51.EXE" ".\hex\HP-01-MCU" HEX
